import { amulet, follower, spell } from './util';

// デコラー: 【クレスト】 are stickers on the leader — permanent effects that stack
// (max 8). 【クレストX】 checks how many are on.
export const DECO = [
  // ---------------- bronze
  follower({
    id: 'e_sticker',
    name: 'シール好き',
    cls: 'deco',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 2,
    art: '🧒',
    art2: '💗',
    text: '【ファンファーレ】クレスト「ハートデコ」を貼る',
    flavor: 'シール帳は、3冊目。',
    fanfare: (c) => {
      c.crest('t_dheart');
    },
  }),
  spell({
    id: 'e_tweezers',
    name: 'デコ用ピンセット',
    cls: 'deco',
    cost: 2,
    rarity: 'bronze',
    art: '🥢',
    text: 'クレスト「スターデコ」を貼る',
    flavor: '0.1ミリのズレも、許さない。',
    spell: (c) => {
      c.crest('t_dstar');
    },
  }),
  follower({
    id: 'e_case',
    name: 'スマホケース職人',
    cls: 'deco',
    cost: 2,
    rarity: 'bronze',
    atk: 2,
    hp: 3,
    art: '📱',
    text: '【ファンファーレ】【クレスト2】カードを1枚引く',
    flavor: '中身より、ケースのほうが高い。',
    fanfare: (c) => {
      if (c.crestAt(2)) c.draw(1);
    },
  }),
  spell({
    id: 'e_glitter',
    name: 'ラメラメ',
    cls: 'deco',
    cost: 1,
    rarity: 'bronze',
    art: '✨',
    text: 'ランダムな相手のフォロワーに2ダメージ\n【クレスト3】かわりに4ダメージ',
    flavor: '目に入ると、ちょっと痛い。',
    spell: (c) => c.pingFollowers(1, c.crestAt(3) ? 4 : 2),
  }),
  follower({
    id: 'e_kawaii',
    name: 'かわいい警察',
    cls: 'deco',
    cost: 3,
    rarity: 'bronze',
    atk: 2,
    hp: 3,
    kw: ['ward'],
    art: '👮‍♀️',
    text: '《守護》\n【ファンファーレ】クレスト「パールデコ」を貼る',
    flavor: '「かわいくない子は、通しません」',
    fanfare: (c) => {
      c.crest('t_dpearl');
    },
  }),
  amulet({
    id: 'e_shop',
    name: 'デコショップ',
    cls: 'deco',
    cost: 3,
    rarity: 'bronze',
    countdown: 3,
    art: '🏬',
    text: '【カウントダウン3】\n【自分のターン開始時】ランダムなデコのクレストを1つ貼る',
    flavor: '入ったら最後、手ぶらじゃ出られない。',
    aiValue: 4,
    turnStart: (c) => c.randomCrest(1),
  }),
  follower({
    id: 'e_idol',
    name: 'デコ盛りアイドル',
    cls: 'deco',
    cost: 4,
    rarity: 'bronze',
    atk: 3,
    hp: 3,
    art: '💃',
    art2: '💝',
    text: '【ファンファーレ】自分のクレスト1つにつき、ランダムな相手のフォロワーかリーダーに1ダメージ',
    flavor: '衣装の重さ、5キロ。',
    fanfare: (c) => c.ping(c.crestCount, 1),
  }),
  spell({
    id: 'e_glue',
    name: 'デコ用ボンド',
    cls: 'deco',
    cost: 2,
    rarity: 'bronze',
    art: '🧴',
    text: 'クレスト「リボンデコ」を貼る。カードを1枚引く',
    flavor: '一度ついたら、二度と取れない。',
    spell: (c) => {
      c.crest('t_dribbon');
      c.draw(1);
    },
  }),
  // ---------------- silver
  follower({
    id: 'e_nail',
    name: 'ネイリスト',
    cls: 'deco',
    cost: 2,
    rarity: 'silver',
    atk: 2,
    hp: 2,
    art: '💅',
    text: '【ファンファーレ】クレスト「ストーンデコ」を貼る',
    flavor: '爪の上の、小さな宇宙。',
    fanfare: (c) => {
      c.crest('t_dstone');
    },
  }),
  follower({
    id: 'e_mirror',
    name: 'デコミラー',
    cls: 'deco',
    cost: 3,
    rarity: 'silver',
    atk: 2,
    hp: 4,
    art: '🪞',
    text: '自分がクレストを貼るたび、カードを1枚引く',
    flavor: '映るたびに、もっと盛りたくなる。',
    aiValue: 3,
    onCrest: (c) => {
      c.draw(1);
    },
  }),
  amulet({
    id: 'e_popup',
    name: 'ポップアップストア',
    cls: 'deco',
    cost: 3,
    rarity: 'silver',
    countdown: 2,
    art: '🎪',
    text: '【カウントダウン2】\n【ファンファーレ】ランダムなデコのクレストを2つ貼る',
    flavor: '期間限定。並ぶしかない。',
    aiValue: 2,
    fanfare: (c) => c.randomCrest(2),
  }),
  follower({
    id: 'e_guardian',
    name: 'デコの守護神',
    cls: 'deco',
    cost: 4,
    rarity: 'silver',
    atk: 3,
    hp: 5,
    kw: ['ward'],
    art: '🛡️',
    art2: '💖',
    text: '《守護》\n【ファンファーレ】【クレスト3】自分のリーダーを5回復',
    flavor: '盛れてる子は、守りたくなる。',
    fanfare: (c) => {
      if (c.crestAt(3)) c.heal(5);
    },
  }),
  spell({
    id: 'e_flash',
    name: 'フラッシュ撮影',
    cls: 'deco',
    cost: 3,
    rarity: 'silver',
    art: '📸',
    text: '相手のフォロワーすべてに1ダメージ\n【クレスト4】かわりに2ダメージ',
    flavor: '盛れすぎて、相手が目をそらした。',
    spell: (c) => c.dmgAll(c.enemies(), c.crestAt(4) ? 2 : 1),
  }),
  follower({
    id: 'e_tower',
    name: '盛り盛りタワー',
    cls: 'deco',
    cost: 5,
    rarity: 'silver',
    atk: 4,
    hp: 5,
    art: '🗼',
    art2: '🎀',
    text: '【ファンファーレ】クレスト「ハートデコ」と「スターデコ」を貼る',
    flavor: '高さ制限、知らない。',
    fanfare: (c) => {
      c.crest('t_dheart');
      c.crest('t_dstar');
    },
  }),
  // ---------------- gold
  amulet({
    id: 'e_itabag',
    name: '痛バッグ',
    cls: 'deco',
    cost: 4,
    rarity: 'gold',
    countdown: 3,
    art: '👜',
    art2: '💝',
    text: '【カウントダウン3】\n【ファンファーレ】ランダムなデコのクレストを3つ貼る',
    flavor: '缶バッジ200個。肩がもげそう。',
    aiValue: 2,
    fanfare: (c) => c.randomCrest(3),
  }),
  follower({
    id: 'e_princess',
    name: 'デコ姫',
    cls: 'deco',
    cost: 5,
    rarity: 'gold',
    atk: 4,
    hp: 5,
    art: '👸',
    art2: '🎀',
    text: '【ファンファーレ】ランダムなデコのクレストを1つ貼る\n自分がクレストを貼るたび、相手のリーダーに1ダメージ',
    flavor: '「デコは、強さよ」',
    aiValue: 3,
    fanfare: (c) => c.randomCrest(1),
    onCrest: (c) => {
      c.face(1);
    },
  }),
  spell({
    id: 'e_blacklight',
    name: 'ブラックライト',
    cls: 'deco',
    cost: 4,
    rarity: 'gold',
    art: '🔦',
    text: '自分のクレスト1つにつき、ランダムな相手のフォロワーに2ダメージ（最大5回）',
    flavor: '暗くすると、デコが本気を出す。',
    spell: (c) => c.pingFollowers(Math.min(5, c.crestCount), 2),
  }),
  follower({
    id: 'e_knight',
    name: 'ラインストーン騎士',
    cls: 'deco',
    cost: 6,
    rarity: 'gold',
    atk: 5,
    hp: 6,
    kw: ['ward'],
    art: '🤺',
    art2: '💎',
    text: '《守護》\n【ファンファーレ】【クレスト5】相手のフォロワーすべてに3ダメージ',
    flavor: '鎧のストーン、全部手貼り。',
    fanfare: (c) => {
      if (c.crestAt(5)) c.dmgAll(c.enemies(), 3);
    },
  }),
  // ---------------- legend
  follower({
    id: 'e_decorina',
    name: 'デコの女神デコリーナ',
    cls: 'deco',
    cost: 5,
    rarity: 'legend',
    atk: 4,
    hp: 5,
    art: '🧚‍♀️',
    art2: '😇',
    text: '【ファンファーレ】クレスト「ハローデコ」を貼る',
    flavor: '「すべての盛りに、祝福を」',
    fanfare: (c) => {
      c.crest('t_dhalo');
    },
  }),
  follower({
    id: 'e_president',
    name: '金ピカ社長',
    cls: 'deco',
    cost: 4,
    rarity: 'legend',
    atk: 3,
    hp: 4,
    art: '🤑',
    art2: '👑',
    text: '【ファンファーレ】クレスト「ゴールドデコ」を貼る',
    flavor: '「金色は、いくらあってもいい」',
    fanfare: (c) => {
      c.crest('t_dgold');
    },
  }),
  follower({
    id: 'e_castle',
    name: 'デコ盛り城',
    cls: 'deco',
    cost: 8,
    rarity: 'legend',
    atk: 6,
    hp: 6,
    kw: ['ward'],
    art: '🏰',
    art2: '💝',
    text: '《守護》\n自分のクレスト1つにつき、このカードのコスト-1\n【ファンファーレ】自分のクレスト1つにつき、相手のフォロワーすべてに1ダメージ（最大4）',
    flavor: 'デコを盛りすぎて、ついに城になった。',
    costFn: (s, card) => -s.players[card.owner].crests.length,
    fanfare: (c) => {
      const n = Math.min(4, c.crestCount);
      if (n) c.dmgAll(c.enemies(), n);
    },
  }),
];
