import { amulet, follower, spell } from './util';

export const TOKENS = [
  follower({
    id: 't_star',
    name: 'SSRスター',
    cls: 'gacha',
    cost: 3,
    rarity: 'gold',
    atk: 3,
    hp: 3,
    kw: ['ward'],
    art: '⭐',
    text: '《守護》',
    flavor: '排出率0.6%の輝き。',
    token: true,
  }),
  follower({
    id: 't_hazure',
    name: 'ハズレくん',
    cls: 'gacha',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 1,
    art: '🥲',
    text: '',
    flavor: 'ハズレでも、場は埋まる。',
    token: true,
  }),
  follower({
    id: 't_atari',
    name: 'アタリくん',
    cls: 'gacha',
    cost: 2,
    rarity: 'silver',
    atk: 2,
    hp: 2,
    kw: ['rush'],
    art: '🤩',
    text: '《突進》',
    flavor: 'アタリが出た瞬間の顔。',
    token: true,
  }),
  spell({
    id: 't_flick',
    name: 'フリック',
    cls: 'swipe',
    cost: 0,
    rarity: 'bronze',
    art: '👉',
    text: 'ランダムな相手のフォロワーかリーダーに1ダメージ',
    flavor: '指先ひとつで、次へ。',
    token: true,
    spell: (c) => c.ping(1, 1),
  }),
  follower({
    id: 't_sakura',
    name: 'サクラ',
    cls: 'stream',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 1,
    art: '🌸',
    text: '',
    flavor: '「わこつ〜」しか言わない。',
    token: true,
  }),
  spell({
    id: 't_clip',
    name: '切り抜き動画',
    cls: 'stream',
    cost: 0,
    rarity: 'bronze',
    art: '✂️',
    text: 'ランダムな相手のフォロワー1体に1ダメージ。いいね+1',
    flavor: '本編より伸びる。',
    token: true,
    spell: (c) => {
      c.dmg(c.pick(c.enemies()), 1);
      c.likes(1);
    },
  }),
  spell({
    id: 't_candy',
    name: 'キャンディ',
    cls: 'sweets',
    cost: 0,
    rarity: 'bronze',
    art: '🍬',
    text: '自分のリーダーを2回復',
    flavor: 'ポケットに常備。',
    token: true,
    spell: (c) => {
      c.heal(2);
    },
  }),
  spell({
    id: 't_skip',
    name: 'スキップ',
    cls: 'swipe',
    cost: 0,
    rarity: 'bronze',
    art: '⏭️',
    text: 'カードを1枚引く',
    flavor: 'おかわりのスキップ。これで最後。',
    token: true,
    spell: (c) => {
      c.draw(1);
    },
  }),
  follower({
    id: 't_dancer',
    name: 'バックダンサー',
    cls: 'swipe',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 1,
    kw: ['rush'],
    art: '💃',
    text: '《突進》',
    flavor: '15秒だけ全力。',
    token: true,
  }),
  // ---------------- ガジェッター パーツ
  follower({
    id: 't_pbolt',
    name: 'ボルトパーツ',
    cls: 'gadget',
    cost: 1,
    rarity: 'bronze',
    atk: 2,
    hp: 2,
    art: '🔩',
    text: '',
    flavor: 'いちばん地味で、いちばん大事。',
    token: true,
    tags: ['part'],
  }),
  follower({
    id: 't_pspring',
    name: 'バネパーツ',
    cls: 'gadget',
    cost: 1,
    rarity: 'bronze',
    atk: 2,
    hp: 1,
    kw: ['rush'],
    art: '🪀',
    text: '《突進》',
    flavor: 'びよーん。',
    token: true,
    tags: ['part'],
  }),
  follower({
    id: 't_pbattery',
    name: 'バッテリーパーツ',
    cls: 'gadget',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 3,
    kw: ['ward'],
    art: '🔋',
    text: '《守護》',
    flavor: '残量100%。',
    token: true,
    tags: ['part'],
  }),
  follower({
    id: 't_pchip',
    name: 'チップパーツ',
    cls: 'gadget',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 1,
    art: '💠',
    text: '【ファンファーレ】カードを1枚引く',
    flavor: '小さいけど、頭がいい。',
    token: true,
    tags: ['part'],
    fanfare: (c) => {
      c.draw(1);
    },
  }),
  // ---------------- トレジャラー 財宝
  spell({
    id: 't_tcoin',
    name: '金貨',
    cls: 'treasure',
    cost: 0,
    rarity: 'bronze',
    art: '🪙',
    text: '相手のリーダーに1ダメージ',
    flavor: 'チャリン。いい音。',
    token: true,
    tags: ['treasure'],
    spell: (c) => {
      c.face(1);
    },
  }),
  spell({
    id: 't_tgem',
    name: '宝石',
    cls: 'treasure',
    cost: 1,
    rarity: 'bronze',
    art: '💎',
    text: '相手のフォロワー1体に2ダメージ',
    flavor: '投げてもいい。高いけど。',
    token: true,
    tags: ['treasure'],
    target: { kind: 'enemyFollower' },
    spell: (c) => {
      c.dmg(c.target, 2);
    },
  }),
  spell({
    id: 't_tcup',
    name: '黄金の杯',
    cls: 'treasure',
    cost: 1,
    rarity: 'bronze',
    art: '🏆',
    text: 'カードを1枚引く。自分のリーダーを2回復',
    flavor: '中身はただのジュース。',
    token: true,
    tags: ['treasure'],
    spell: (c) => {
      c.draw(1);
      c.heal(2);
    },
  }),
  spell({
    id: 't_tcrown',
    name: '王冠',
    cls: 'treasure',
    cost: 1,
    rarity: 'bronze',
    art: '👑',
    text: '自分のフォロワーすべてを+1/+0',
    flavor: 'かぶると、ちょっと強くなった気がする。',
    token: true,
    tags: ['treasure'],
    spell: (c) => {
      c.buffAll(c.allies(), 1, 0);
    },
  }),
  // ---------------- ハモラー
  spell({
    id: 't_chorus',
    name: 'コーラス',
    cls: 'harmony',
    cost: 0,
    rarity: 'bronze',
    art: '🎶',
    text: 'カードを1枚引く。自分のリーダーを1回復',
    flavor: 'ラ〜♪（3度上）',
    token: true,
    spell: (c) => {
      c.draw(1);
      c.heal(1);
    },
  }),
  // ---------------- クラッシャー
  amulet({
    id: 't_junk',
    name: 'ガラクタ',
    cls: 'crash',
    cost: 0,
    rarity: 'bronze',
    countdown: 2,
    art: '🗑️',
    art2: '🔩',
    text: '【カウントダウン2】\n【ラストワード】ランダムな相手のフォロワーかリーダーに1ダメージ',
    flavor: '壊すために、ある。',
    token: true,
    tags: ['junk'],
    lastWords: (c) => c.ping(1, 1),
  }),
  // ---------------- レンジャー
  follower({
    id: 't_cadet',
    name: '研修隊員',
    cls: 'ranger',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 1,
    art: '🧑‍🚒',
    text: '',
    flavor: '変身ポーズの練習中。',
    token: true,
  }),
  // ---------------- スペラー
  spell({
    id: 't_mspark',
    name: 'マジカルスパーク',
    cls: 'witch',
    cost: 0,
    rarity: 'bronze',
    art: '✨',
    text: 'ランダムな相手のフォロワーに1ダメージ',
    flavor: 'ちいさな魔法も、魔法は魔法。',
    token: true,
    spell: (c) => c.pingFollowers(1, 1),
  }),
  follower({
    id: 't_familiar',
    name: '使い魔',
    cls: 'witch',
    cost: 2,
    rarity: 'bronze',
    atk: 2,
    hp: 2,
    art: '🦇',
    text: '',
    flavor: 'ご主人の言うことは、半分聞く。',
    token: true,
  }),
  // ---------------- ステラー
  spell({
    id: 't_cash',
    name: '売上金',
    cls: 'minimal',
    cost: 0,
    rarity: 'bronze',
    art: '💴',
    text: 'ランダムな相手のフォロワーかリーダーに1ダメージ',
    flavor: '300円で売れた。送料は400円。',
    token: true,
    spell: (c) => c.ping(1, 1),
  }),
  // ---------------- ジュエラー
  amulet({
    id: 't_crystal',
    name: '結晶',
    cls: 'jewel',
    cost: 0,
    rarity: 'bronze',
    countdown: 2,
    art: '💠',
    text: '【ラストワード】中のフォロワーが出てくる',
    flavor: 'まだ、眠っている。',
    token: true,
    lastWords: (c) => {
      c.hatch();
    },
  }),
  // ---------------- デコラー クレスト（リーダーに貼るデコ）
  amulet({
    id: 't_dheart',
    name: 'ハートデコ',
    cls: 'deco',
    cost: 0,
    rarity: 'bronze',
    art: '💗',
    text: '【クレスト】\n【自分のターン終了時】自分のリーダーを1回復',
    flavor: 'ハートは、いくつあってもいい。',
    token: true,
    tags: ['crest'],
    turnEnd: (c) => {
      c.heal(1);
    },
  }),
  amulet({
    id: 't_dstar',
    name: 'スターデコ',
    cls: 'deco',
    cost: 0,
    rarity: 'bronze',
    art: '⭐',
    text: '【クレスト】\n【自分のターン終了時】ランダムな相手のフォロワーかリーダーに1ダメージ',
    flavor: 'キラッと光って、チクッと刺さる。',
    token: true,
    tags: ['crest'],
    turnEnd: (c) => c.ping(1, 1),
  }),
  amulet({
    id: 't_dribbon',
    name: 'リボンデコ',
    cls: 'deco',
    cost: 0,
    rarity: 'bronze',
    art: '🎀',
    text: '【クレスト】\n自分のフォロワーが場に出るたび、ランダムな相手のフォロワーに1ダメージ',
    flavor: '結び目は、ほどけない。',
    token: true,
    tags: ['crest'],
    onSummon: (c) => c.pingFollowers(1, 1),
  }),
  amulet({
    id: 't_dpearl',
    name: 'パールデコ',
    cls: 'deco',
    cost: 0,
    rarity: 'bronze',
    art: '⚪',
    text: '【クレスト】\n【自分のターン開始時】自分のリーダーを1回復',
    flavor: '上品さは、守りにもなる。',
    token: true,
    tags: ['crest'],
    turnStart: (c) => {
      c.heal(1);
    },
  }),
  amulet({
    id: 't_dstone',
    name: 'ストーンデコ',
    cls: 'deco',
    cost: 0,
    rarity: 'bronze',
    art: '💎',
    text: '【クレスト】\n自分がスペルを使うたび、相手のリーダーに1ダメージ',
    flavor: 'ラインストーン、ひと粒ずつ手貼り。',
    token: true,
    tags: ['crest'],
    onPlay: (c) => {
      if (c.isSpell(c.other)) c.face(1);
    },
  }),
  amulet({
    id: 't_dhalo',
    name: 'ハローデコ',
    cls: 'deco',
    cost: 0,
    rarity: 'bronze',
    art: '😇',
    text: '【クレスト】\n【自分のターン終了時】ランダムな相手のフォロワーかリーダーに2ダメージ。自分のリーダーを1回復',
    flavor: '女神さまのデコは、光ってる。',
    token: true,
    tags: ['crest'],
    turnEnd: (c) => {
      c.ping(1, 2);
      c.heal(1);
    },
  }),
  amulet({
    id: 't_dgold',
    name: 'ゴールドデコ',
    cls: 'deco',
    cost: 0,
    rarity: 'bronze',
    art: '👑',
    text: '【クレスト】\n【自分のターン開始時】カードを1枚引く',
    flavor: '金ピカは、正義。',
    token: true,
    tags: ['crest'],
    turnStart: (c) => {
      c.draw(1);
    },
  }),
  // ---------------- パペッター
  follower({
    id: 't_puppet',
    name: '人形',
    cls: 'puppet',
    cost: 0,
    rarity: 'bronze',
    atk: 1,
    hp: 1,
    kw: ['rush'],
    art: '🪆',
    text: '《突進》\n相手のターン終了時、このフォロワーは消える',
    flavor: '糸が引かれるのを、待っている。',
    token: true,
    fleeting: true,
    tags: ['puppet'],
  }),
  follower({
    id: 't_matry2',
    name: 'ミニマトリョーシカ',
    cls: 'puppet',
    cost: 2,
    rarity: 'bronze',
    atk: 2,
    hp: 2,
    art: '🪆',
    text: '【ラストワード】「プチマトリョーシカ」を1体出す',
    flavor: '開けると、まだいる。',
    token: true,
    tags: ['puppet'],
    lastWords: (c) => {
      c.summon('t_matry3');
    },
  }),
  follower({
    id: 't_matry3',
    name: 'プチマトリョーシカ',
    cls: 'puppet',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 1,
    kw: ['rush'],
    art: '🪆',
    text: '《突進》',
    flavor: 'これで、最後。……たぶん。',
    token: true,
    tags: ['puppet'],
  }),
];
