import { follower, spell } from './util';

export const TOKENS = [
  follower({
    id: 't_star',
    name: 'SSRスター',
    cls: 'gacha',
    cost: 3,
    rarity: 'gold',
    atk: 3,
    hp: 3,
    kw: ['ward'],
    art: '⭐',
    text: '《守護》',
    flavor: '排出率0.6%の輝き。',
    token: true,
  }),
  follower({
    id: 't_hazure',
    name: 'ハズレくん',
    cls: 'gacha',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 1,
    art: '🥲',
    text: '',
    flavor: 'ハズレでも、場は埋まる。',
    token: true,
  }),
  follower({
    id: 't_atari',
    name: 'アタリくん',
    cls: 'gacha',
    cost: 2,
    rarity: 'silver',
    atk: 2,
    hp: 2,
    kw: ['rush'],
    art: '🤩',
    text: '《突進》',
    flavor: 'アタリが出た瞬間の顔。',
    token: true,
  }),
  spell({
    id: 't_flick',
    name: 'フリック',
    cls: 'swipe',
    cost: 0,
    rarity: 'bronze',
    art: '👉',
    text: 'ランダムな相手のフォロワーかリーダーに1ダメージ',
    flavor: '指先ひとつで、次へ。',
    token: true,
    spell: (c) => c.ping(1, 1),
  }),
  follower({
    id: 't_sakura',
    name: 'サクラ',
    cls: 'stream',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 1,
    art: '🌸',
    text: '',
    flavor: '「わこつ〜」しか言わない。',
    token: true,
  }),
  spell({
    id: 't_clip',
    name: '切り抜き動画',
    cls: 'stream',
    cost: 0,
    rarity: 'bronze',
    art: '✂️',
    text: 'ランダムな相手のフォロワー1体に1ダメージ。いいね+1',
    flavor: '本編より伸びる。',
    token: true,
    spell: (c) => {
      c.dmg(c.pick(c.enemies()), 1);
      c.likes(1);
    },
  }),
  spell({
    id: 't_candy',
    name: 'キャンディ',
    cls: 'sweets',
    cost: 0,
    rarity: 'bronze',
    art: '🍬',
    text: '自分のリーダーを2回復',
    flavor: 'ポケットに常備。',
    token: true,
    spell: (c) => {
      c.heal(2);
    },
  }),
  spell({
    id: 't_skip',
    name: 'スキップ',
    cls: 'swipe',
    cost: 0,
    rarity: 'bronze',
    art: '⏭️',
    text: 'カードを1枚引く',
    flavor: 'おかわりのスキップ。これで最後。',
    token: true,
    spell: (c) => {
      c.draw(1);
    },
  }),
  follower({
    id: 't_dancer',
    name: 'バックダンサー',
    cls: 'swipe',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 1,
    kw: ['rush'],
    art: '💃',
    text: '《突進》',
    flavor: '15秒だけ全力。',
    token: true,
  }),
  // ---------------- ガジェッター パーツ
  follower({
    id: 't_pbolt',
    name: 'ボルトパーツ',
    cls: 'gadget',
    cost: 1,
    rarity: 'bronze',
    atk: 2,
    hp: 2,
    art: '🔩',
    text: '',
    flavor: 'いちばん地味で、いちばん大事。',
    token: true,
    tags: ['part'],
  }),
  follower({
    id: 't_pspring',
    name: 'バネパーツ',
    cls: 'gadget',
    cost: 1,
    rarity: 'bronze',
    atk: 2,
    hp: 1,
    kw: ['rush'],
    art: '🪀',
    text: '《突進》',
    flavor: 'びよーん。',
    token: true,
    tags: ['part'],
  }),
  follower({
    id: 't_pbattery',
    name: 'バッテリーパーツ',
    cls: 'gadget',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 3,
    kw: ['ward'],
    art: '🔋',
    text: '《守護》',
    flavor: '残量100%。',
    token: true,
    tags: ['part'],
  }),
  follower({
    id: 't_pchip',
    name: 'チップパーツ',
    cls: 'gadget',
    cost: 1,
    rarity: 'bronze',
    atk: 1,
    hp: 1,
    art: '💠',
    text: '【ファンファーレ】カードを1枚引く',
    flavor: '小さいけど、頭がいい。',
    token: true,
    tags: ['part'],
    fanfare: (c) => {
      c.draw(1);
    },
  }),
];
