import type { ClassId, Keyword, Rarity } from './types';

export interface ClassMeta {
  id: ClassId;
  name: string;
  /** one-word tagline */
  tag: string;
  emoji: string;
  color: string;
  color2: string;
  leaderName: string;
  leaderArt: string;
  mechanic: string;
  mechanicDesc: string;
  counter: 'luck' | 'likes' | 'sweet' | 'combo' | 'level' | 'parts' | 'treasure' | 'harmony' | 'broken' | 'rally' | 'spells' | 'handless' | 'jewel' | 'chapter' | 'crest' | 'spicy' | 'fulfill' | 'puppet' | 'none';
  /** short pitch shown on class select */
  pitch: string;
  /** leader lines used in battle */
  lines: { start: string; evolve: string; win: string; lose: string; hurt: string; fever: string };
}

export const CLASSES: Record<ClassId, ClassMeta> = {
  neutral: {
    id: 'neutral',
    name: 'ニュートラル',
    tag: '共通',
    emoji: '⚪',
    color: '#c9d3ea',
    color2: '#8a97b8',
    leaderName: '—',
    leaderArt: '⚪',
    mechanic: '',
    mechanicDesc: '',
    counter: 'none',
    pitch: 'どのクラスでも使える',
    lines: { start: '', evolve: '', win: '', lose: '', hurt: '', fever: '' },
  },
  gacha: {
    id: 'gacha',
    name: 'ガチャラー',
    tag: '一発逆転',
    emoji: '🎰',
    color: '#ffc531',
    color2: '#ff3fa4',
    leaderName: 'ガチャラー ルーレ',
    leaderArt: '👸',
    mechanic: 'ガチャ・運気',
    mechanicDesc:
      'ガチャを引くとN/R/SR/SSRのどれかが出て効果が変わる。SSR以外が出るたび運気+1。運気6（天井）で次はSSR確定！',
    counter: 'luck',
    pitch: '回せ。SSRが全部ひっくり返す。',
    lines: {
      start: '今日の運勢、確かめてみます？',
      evolve: '確定演出、入りましたわ！',
      win: 'SSRは、引くまで引くのですわ！',
      lose: '……次の天井で、取り返しますわ',
      hurt: '爆死ですわ〜！？',
      fever: '虹色演出、キマシタワー！',
    },
  },
  stream: {
    id: 'stream',
    name: 'ストリーマー',
    tag: '拡散爆発',
    emoji: '📱',
    color: '#ff4f9a',
    color2: '#27d8ff',
    leaderName: 'ストリーマー バズリン',
    leaderArt: '🦊',
    mechanic: 'いいね・バズ',
    mechanicDesc:
      'カードをプレイするたびいいね+1。【バズX】はいいねをX消費して強力な追加効果を発動！',
    counter: 'likes',
    pitch: 'いいねを集めて、一気にバズれ。',
    lines: {
      start: 'こんバズ〜！ 今日もいいねよろしく！',
      evolve: '神回きたーーー！',
      win: '高評価・チャンネル登録よろしくね！',
      lose: '配信、切り忘れてた……？',
      hurt: 'コメ欄荒れてる〜！',
      fever: 'トレンド1位、いただきっ！',
    },
  },
  sweets: {
    id: 'sweets',
    name: 'シュガラー',
    tag: '回復増強',
    emoji: '🍰',
    color: '#ff9f6e',
    color2: '#7ff0c8',
    leaderName: 'シュガラー アマミ',
    leaderArt: '🐰',
    mechanic: '糖度・シュガーハイ',
    mechanicDesc:
      '自分のリーダーを回復するたび、その数値だけ糖度が上がる（満タンでもOK）。【シュガーハイX】は糖度がX以上なら発動！',
    counter: 'sweet',
    pitch: '甘やかして、デカくして、押しつぶす。',
    lines: {
      start: 'いらっしゃいませ♪ 甘〜い時間にしましょ',
      evolve: 'デコレーション、完成です！',
      win: 'ごちそうさまでした♪',
      lose: '焦げちゃった……',
      hurt: 'クリームが崩れる〜！',
      fever: '糖分、限界突破です！',
    },
  },
  swipe: {
    id: 'swipe',
    name: 'スワイパー',
    tag: '秒速連打',
    emoji: '⚡',
    color: '#ffe53d',
    color2: '#25e0ff',
    leaderName: 'スワイパー シュン',
    leaderArt: '🐆',
    mechanic: 'コンボ',
    mechanicDesc:
      '1ターンにカードを出すほどコンボが増える。【コンボX】はこのターンに他のカードをX枚以上プレイしていれば発動！',
    counter: 'combo',
    pitch: '秒で出して、秒で殴る。',
    lines: {
      start: '3秒で終わらせる。',
      evolve: '加速、加速、加速！',
      win: 'はい、次。',
      lose: '……巻き戻し、できない？',
      hurt: 'ちょ、速っ！？',
      fever: '倍速じゃ足りない、10倍速だ！',
    },
  },
  gamer: {
    id: 'gamer',
    name: 'ゲーマー',
    tag: '育成無双',
    emoji: '🎮',
    color: '#3dff95',
    color2: '#a066ff',
    leaderName: 'ゲーマー レベル丸',
    leaderArt: '🐼',
    mechanic: 'レベル・課金',
    mechanicDesc:
      '【レベル】を持つフォロワーは攻撃するとEXP+1（相手のフォロワーを倒したら+2）。たまるとレベルアップして体力も全回復！【課金X】はPPがX以上あれば、Xを払って強化版でプレイ。',
    counter: 'level',
    pitch: 'レベルを上げて、物理で殴れ。',
    lines: {
      start: 'よろしくお願いしまーす（ガチ勢）',
      evolve: 'レベルアップ！ テレレレッテッテー！',
      win: 'GG！ 経験値うまい！',
      lose: 'ラグかった。絶対ラグかった。',
      hurt: 'HPミリなんだけど！？',
      fever: '無双モード、突入！',
    },
  },
  gadget: {
    id: 'gadget',
    name: 'ガジェッター',
    tag: '合体変形',
    emoji: '🔧',
    color: '#ff8a1f',
    color2: '#2ee6d6',
    leaderName: 'ガジェッター ネジコ',
    leaderArt: '🦫',
    mechanic: 'パーツ・合体',
    mechanicDesc:
      'カードの効果で「パーツ」（4種類）を手に入れる。パーツはそのまま出してもいいし、【合体X】で手札から最大X枚取り込んでもいい。出した／取り込んだパーツの種類がそろうほど【コンプリートX】が発動！',
    counter: 'parts',
    pitch: 'パーツを集めて、合体して、最強ロボ。',
    lines: {
      start: 'ネジ1本から、世界を変えるよ！',
      evolve: '変形、かんりょー！',
      win: '設計図どおり、完ぺき！',
      lose: '……どこのネジがゆるんでた？',
      hurt: 'あっ、部品が飛んだ！',
      fever: 'フルパワー合体、いっくよー！',
    },
  },
  treasure: {
    id: 'treasure',
    name: 'トレジャラー',
    tag: '一攫千金',
    emoji: '💰',
    color: '#ffc23d',
    color2: '#c4174b',
    leaderName: 'トレジャラー キンカ',
    leaderArt: '🦜',
    mechanic: '財宝',
    mechanicDesc:
      'カードの効果で「財宝」（金貨・宝石・黄金の杯・王冠の4種類）を手に入れる。財宝は安くて便利なスペル。使った財宝の枚数がたまるほど【財宝X】が発動！',
    counter: 'treasure',
    pitch: 'お宝ザクザク、ぜんぶ使って成り上がれ。',
    lines: {
      start: 'お宝のにおいがするねぇ！',
      evolve: '大当たり、ゴールドラッシュ！',
      win: '戦利品、ぜーんぶいただき！',
      lose: '……宝の地図、逆さまだった？',
      hurt: 'あたしの金貨がー！',
      fever: '財宝フィーバー、開・封！',
    },
  },
  harmony: {
    id: 'harmony',
    name: 'ハモラー',
    tag: '共鳴',
    emoji: '🎤',
    color: '#4de1ff',
    color2: '#ff4fd8',
    leaderName: 'ハモラー リリカ',
    leaderArt: '🐬',
    mechanic: 'ハモり',
    mechanicDesc:
      '自分の山札が偶数枚のとき「ハモり」状態。【ハモり】の効果は、そのとき偶数なら発動！ ドローや「コーラス」を山札に加えるカードで偶数・奇数を切り替えよう。',
    counter: 'harmony',
    pitch: '山札とハモって、会場ごと震わせろ。',
    lines: {
      start: 'マイクチェック、ワン・ツー！',
      evolve: 'サビ、いっくよー！',
      win: 'アンコール、ありがとー！',
      lose: '……音、外しちゃった。',
      hurt: 'ノイズ入った！',
      fever: '全員でハモって！',
    },
  },
  crash: {
    id: 'crash',
    name: 'クラッシャー',
    tag: '破壊衝動',
    emoji: '💥',
    color: '#ff4d2e',
    color2: '#6a6a8a',
    leaderName: 'クラッシャー ゴウ',
    leaderArt: '🦏',
    mechanic: '破壊・いけにえ',
    mechanicDesc:
      '自分のカードが壊れるほど強くなる。【いけにえ】で自分の場のカードをわざと壊して効果を発動！ 壊れたカードの【ラストワード】も発動して一石二鳥。このバトルで壊れた自分のカードの数が【破壊X】の条件。',
    counter: 'broken',
    pitch: 'ぶっ壊して、スッキリ。壊れたものも全部チカラ。',
    lines: {
      start: 'ストレス、ぜんぶ壊してやる！',
      evolve: 'まだまだ壊し足りねぇ！',
      win: 'あースッキリした！',
      lose: '……オレが、壊された……？',
      hurt: 'いってぇ！ 倍返しだ！',
      fever: 'ぜーんぶ、ぶっ壊せ！',
    },
  },
  ranger: {
    id: 'ranger',
    name: 'レンジャー',
    tag: '集結変身',
    emoji: '🦸',
    color: '#ff2e4d',
    color2: '#ffd23d',
    leaderName: 'レンジャー レッド',
    leaderArt: '🦸',
    mechanic: '連携・変身',
    mechanicDesc:
      '仲間をどんどん場に出そう。このバトルで場に出た自分のフォロワーの数が【連携X】の条件。カードの力で進化ポイントを使わずに「変身（進化）」でき、仲間が進化するたびに発動するカードも！',
    counter: 'rally',
    pitch: 'みんな集まれ！ 変身して、必殺技でキメろ。',
    lines: {
      start: 'ドパレンジャー、出動！',
      evolve: '変身ッ！',
      win: '正義は、勝つ！',
      lose: 'ここで……終われない……！',
      hurt: 'まだだ、まだ戦える！',
      fever: '必殺・ドパミンバースト！',
    },
  },
  witch: {
    id: 'witch',
    name: 'スペラー',
    tag: '魔力充填',
    emoji: '🪄',
    color: '#9b5cff',
    color2: '#ff8de8',
    leaderName: 'スペラー ルル',
    leaderArt: '🧙‍♀️',
    mechanic: 'スペルブースト',
    mechanicDesc:
      '【スペルブースト】を持つカードは、手札にあるあいだ自分がスペルを使うたびにブースト+1（カードに✨数字で表示）。コストが下がったり、威力が上がったり。スペルを連打して魔法を育てよう！',
    counter: 'spells',
    pitch: 'スペルを撃つほど、魔法が育つ。',
    lines: {
      start: 'マジカル☆スタート！',
      evolve: '魔力、全開！',
      win: '今日の魔法も、大成功♪',
      lose: '呪文、かんじゃった……',
      hurt: 'きゃっ！ 魔法障壁が！',
      fever: 'マジカル☆フルバースト！',
    },
  },
  minimal: {
    id: 'minimal',
    name: 'ステラー',
    tag: '断捨離',
    emoji: '🧹',
    color: '#34e0b0',
    color2: '#7a8cff',
    leaderName: 'ステラー スッキリ',
    leaderArt: '🦦',
    mechanic: 'ハンドレス・捨てる',
    mechanicDesc:
      '手札が少ないほど強い。【ハンドレスX】は手札がX枚以下なら発動。手札を「捨てる」と【捨てられた時】を持つカードが発動（捨てるカードは自分で選べる）！ 手札を使い切ったら【予約ドロー】で次のターンにまとめて補充。',
    counter: 'handless',
    pitch: '捨てるほど、身軽で強い。',
    lines: {
      start: 'いらないものは、ぜんぶ捨てよっか。',
      evolve: '身軽になったら、本気出す！',
      win: '部屋も試合も、スッキリ！',
      lose: '……捨てすぎた、かも。',
      hurt: 'ちょっと、散らかさないで！',
      fever: '大掃除フィーバー！',
    },
  },
  jewel: {
    id: 'jewel',
    name: 'ジュエラー',
    tag: '変幻自在',
    emoji: '💎',
    color: '#ff7ad9',
    color2: '#7af0ff',
    leaderName: 'ジュエラー キララ',
    leaderArt: '🦢',
    mechanic: '結晶・アクセラレート・エンハンス',
    mechanicDesc:
      'PPが足りないときは【アクセラレート】（安いスペルとして使う）や【結晶】（カウントダウン後にフォロワーが出てくるアミュレット）、PPが多いときは【エンハンス】（強化版）。同じカードが、PPによって姿を変える！',
    counter: 'jewel',
    pitch: 'PPが少なくても多くても、ずっと輝ける。',
    lines: {
      start: 'キラキラ、はじめよっ！',
      evolve: 'もっと、輝いて！',
      win: 'いちばん輝いたのは、わたし！',
      lose: '……くすんじゃった。',
      hurt: '傷がついちゃう！',
      fever: 'ブリリアント・フィーバー！',
    },
  },
  novel: {
    id: 'novel',
    name: 'ノベラー',
    tag: '白黒二面',
    emoji: '📖',
    color: '#e8dcc0',
    color2: '#4a2a7a',
    leaderName: 'ノベラー シオリ',
    leaderArt: '🐈',
    mechanic: '白の章・黒の章',
    mechanicDesc:
      'リーダーは「白の章」か「黒の章」のどちらかを開いている（最初は白）。【白の章】の効果は白のとき、【黒の章】の効果は黒のときに発動。「ページをめくる」と章が入れかわる。白は守りと回復、黒は攻撃と破壊！',
    counter: 'chapter',
    pitch: '白で守って、黒で刺す。物語は、めくるたびに転がる。',
    lines: {
      start: 'さあ、ページを開こうか。',
      evolve: '物語は、ここからが本番！',
      win: 'めでたし、めでたし。',
      lose: 'バッドエンド……書き直し！',
      hurt: '展開が重い……！',
      fever: 'クライマックス、突入！',
    },
  },
  deco: {
    id: 'deco',
    name: 'デコラー',
    tag: '盛り盛り',
    emoji: '💝',
    color: '#ff9ad5',
    color2: '#ffe14d',
    leaderName: 'デコラー ミル',
    leaderArt: '🐹',
    mechanic: 'クレスト（デコ）',
    mechanicDesc:
      '【クレスト】はリーダーに貼る「デコ」。一度貼ったら試合が終わるまでずっと効果が続き、重ねて貼れる（最大8個）。貼ったデコの数が【クレストX】の条件。盛れば盛るほど強くなる！',
    counter: 'crest',
    pitch: 'デコって、盛って、ずっとかわいく強い。',
    lines: {
      start: '今日も盛れてる？',
      evolve: 'デコ盛り、マシマシ！',
      win: '映えすぎて勝っちゃった♡',
      lose: '……デコが、はがれた。',
      hurt: 'ネイル欠けたんだけど！？',
      fever: 'キラッキラ、フルデコ！',
    },
  },
  spicy: {
    id: 'spicy',
    name: 'ゲキカラー',
    tag: '激辛上等',
    emoji: '🌶️',
    color: '#ff3b1f',
    color2: '#ffb000',
    leaderName: 'ゲキカラー ホムラ',
    leaderArt: '🐵',
    mechanic: '激辛・ピンチ',
    mechanicDesc:
      '【激辛X】は自分のリーダーがXダメージを受けるかわりに強い効果。自分のリーダーの体力が少ないほど【ピンチX】（体力X以下で発動）が火を噴く。攻めて攻めて、汗だくで勝て！',
    counter: 'spicy',
    pitch: 'からい！ いたい！ でも止まらない！',
    lines: {
      start: '激辛チャレンジ、スタート！',
      evolve: '辛さレベル、MAX！',
      win: '完食！ ごちそうさま！',
      lose: '……水、ください……',
      hurt: 'からっ！ いてっ！',
      fever: '地獄の激辛、いっきまーす！',
    },
  },
  shrine: {
    id: 'shrine',
    name: 'オマモラー',
    tag: '願掛け',
    emoji: '⛩️',
    color: '#ff5a5a',
    color2: '#f2e6c8',
    leaderName: 'オマモラー コマ',
    leaderArt: '🐶',
    mechanic: '成就・祈願',
    mechanicDesc:
      'お守り（カウントダウン付きアミュレット）をたくさん置こう。カウントダウンが0になって願いが叶う（成就）と、お守りの【ラストワード】と「成就するたび」の効果が発動！ 「祈願」でカウントダウンを早められる。成就した数が【成就X】の条件。',
    counter: 'fulfill',
    pitch: 'お願い、叶えて。叶ったら、ぜんぶ力になる。',
    lines: {
      start: 'お参り、すませてきました！',
      evolve: 'ご利益、いただきます！',
      win: '願いは、叶うもの！',
      lose: '……おみくじ、凶だった。',
      hurt: 'バチが当たった！？',
      fever: '大吉フィーバー！',
    },
  },
  puppet: {
    id: 'puppet',
    name: 'パペッター',
    tag: '人形劇',
    emoji: '🎭',
    color: '#b48cff',
    color2: '#ff5a7a',
    leaderName: 'パペッター ノア',
    leaderArt: '🤹',
    mechanic: '人形・操演',
    mechanicDesc:
      '「人形」（0コスト 1/1 《突進》）を手札に加えて戦う。人形はタダで出せて、出たターンから相手のフォロワーに攻撃できる（相手のターン終了時に消える）！ 人形が出たり壊れたりするたびに動くカードも。このバトルで出した人形の数が【操演X】の条件。',
    counter: 'puppet',
    pitch: 'さあ、開演。糸の先で、全部踊らせる。',
    lines: {
      start: '開演のベルが鳴ったよ。',
      evolve: '糸が、もっと強く張る……！',
      win: 'カーテンコール、ありがとう。',
      lose: '……糸が、切れちゃった。',
      hurt: 'お人形が泣いてる！',
      fever: '全員で、踊って！',
    },
  },
};

export const PLAYABLE_CLASSES: ClassId[] = ['gacha', 'stream', 'sweets', 'swipe', 'gamer', 'gadget', 'treasure', 'harmony', 'crash', 'ranger', 'witch', 'minimal', 'jewel', 'novel', 'deco', 'spicy', 'shrine', 'puppet'];

export interface KeywordMeta {
  name: string;
  icon: string;
  desc: string;
}

export const KEYWORDS: Record<Keyword, KeywordMeta> = {
  ward: { name: '守護', icon: '🛡️', desc: '相手はこのフォロワーを倒すまで、他のフォロワーやリーダーを攻撃できない。' },
  storm: { name: '疾走', icon: '💨', desc: '場に出たターンから、フォロワーにもリーダーにも攻撃できる。' },
  rush: { name: '突進', icon: '🐗', desc: '場に出たターンから、フォロワーに攻撃できる。' },
  bane: { name: '必殺', icon: '☠️', desc: 'ダメージを与えたフォロワーを破壊する。' },
  drain: { name: 'ドレイン', icon: '💗', desc: '攻撃でダメージを与えたとき、その分だけ自分のリーダーを回復。' },
  ambush: { name: '潜伏', icon: '👻', desc: '攻撃するまで、相手に攻撃されず、能力で選ばれない。' },
  barrier: { name: 'バリア', icon: '🧿', desc: '次に受けるダメージを1回だけ0にする。' },
  aura: { name: 'オーラ', icon: '✨', desc: '相手のスペルや能力で選ばれない。' },
  twin: { name: '連撃', icon: '⚔️', desc: '1ターンに2回攻撃できる。' },
};

/** ability labels that appear in 【】 in card text */
export const ABILITIES: Record<string, string> = {
  ファンファーレ: 'カードを手札から出したときに発動。',
  ラストワード: '破壊されたときに発動。',
  進化時: '進化させたときに発動。超進化でも発動する。',
  超進化時: '超進化させたときに発動。',
  攻撃時: 'このフォロワーが攻撃するときに発動。',
  交戦時: 'このフォロワーがフォロワーと戦うときに発動。',
  カウントダウン3: '自分のターン開始時に1減り、0になると破壊される。',
  カウントダウン2: '自分のターン開始時に1減り、0になると破壊される。',
  カウントダウン4: '自分のターン開始時に1減り、0になると破壊される。',
  カウントダウン1: '自分のターン開始時に1減り、0になると破壊される。',
  '自分のターン開始時': '自分のターンのはじめに発動。',
  '自分のターン終了時': '自分のターンのおわりに発動。',
  ガチャ: 'N/R/SR/SSRのどれかを引く。SSR以外なら運気+1。運気6で次はSSR確定。',
  確変: '次のガチャがSR以上確定になる。',
  運気: 'ガチャでSSRが出る確率が上がる。6で天井（SSR確定）。',
  いいね: 'カードをプレイするたびに1増える。バズで消費する。',
  バズ3: 'いいねが3以上あれば、3消費して発動。',
  バズ4: 'いいねが4以上あれば、4消費して発動。',
  バズ5: 'いいねが5以上あれば、5消費して発動。',
  パーツ: 'ガジェッターのトークン（ボルト・バネ・バッテリー・チップの4種類）。出しても合体に使ってもいい。',
  ページをめくる: '白の章⇄黒の章を入れかえる。',
  白の章: 'リーダーが白の章を開いているときに発動。',
  黒の章: 'リーダーが黒の章を開いているときに発動。',
  クレスト: 'リーダーに貼る永続効果（デコ）。試合が終わるまでずっと続き、重ねて貼れる（最大8個）。',
  祈願: '自分のアミュレットすべてのカウントダウンを1進める。',
  成就: 'アミュレットのカウントダウンが0になること（願いが叶う）。',
  人形: 'パペッターのトークン（0コスト 1/1 《突進》、相手のターン終了時に消える）。マトリョーシカなど（人形）と書かれたカードも人形として数える。',
  お守り: 'オマモラーのカウントダウン付きアミュレット。カウントダウンが0になると「成就」して、ラストワードが発動する。',
  激辛: '自分のリーダーにダメージを与えて、強力な効果を得る。受けたダメージはこのバトル中ずっと数えられる。',
  いけにえ: '自分の場の他のカード1つを破壊する（「ガラクタ」→【ラストワード】持ち→コストの低いカードの順に選ばれる）。',
  ガラクタ: 'クラッシャーのトークン（0コストのアミュレット）。壊れると相手に1ダメージ。【いけにえ】で真っ先に選ばれる。',
  スペルブースト: '手札にあるあいだ、自分がスペルを使うたびにブースト+1（カードに✨で表示）。',
  捨てられた時: '効果で手札から捨てられたときに発動。',
  結晶から出たとき: '「結晶」のカウントダウンが0になって、このフォロワーが出てきたときに発動。',
  結晶: '【結晶】で出したアミュレット。カウントダウンが0になると中のフォロワーが出てくる（ファンファーレは発動しないが、《突進》を得て出たターンから相手のフォロワーに攻撃できる）。',
  進化ポイント: '進化に使うポイント。カードの効果で増やせる。',
  財宝: 'トレジャラーのトークン（金貨・宝石・黄金の杯・王冠の4種類のスペル）。使った枚数が【財宝X】の条件になる。',
  ハモり: '自分の山札が偶数枚なら発動。',
  コーラス: 'ハモラーのトークン（0コストのスペル。カードを1枚引く）。山札に加えると偶数・奇数が入れかわる。',
  バズ6: 'いいねが6以上あれば、6消費して発動。',
  バズ10: 'いいねが10以上あれば、10消費して発動。',
  シュガーハイ10: '糖度が10以上なら発動（糖度は消費しない）。',
  シュガーハイ15: '糖度が15以上なら発動（糖度は消費しない）。',
  シュガーハイ20: '糖度が20以上なら発動（糖度は消費しない）。',
  コンボ2: 'このターン、他のカードを2枚以上プレイしていれば発動。',
  コンボ3: 'このターン、他のカードを3枚以上プレイしていれば発動。',
  コンボ4: 'このターン、他のカードを4枚以上プレイしていれば発動。',
  課金3: 'PPが3以上あれば、3PP払って強化版でプレイ。',
  課金4: 'PPが4以上あれば、4PP払って強化版でプレイ。',
  課金5: 'PPが5以上あれば、5PP払って強化版でプレイ。',
  課金6: 'PPが6以上あれば、6PP払って強化版でプレイ。',
  課金7: 'PPが7以上あれば、7PP払って強化版でプレイ。',
  課金9: 'PPが9以上あれば、9PP払って強化版でプレイ。',
  課金10: 'PPが10あれば、10PP払って強化版でプレイ。',
  レベル: '攻撃するとEXP+1（相手のフォロワーを倒したら+2）。たまるとレベルアップして強くなり、体力も全回復する。',
};

export const RARITY: Record<Rarity, { name: string; short: string; color: string; craft: number; dust: number; order: number }> = {
  bronze: { name: 'ブロンズ', short: 'B', color: '#d08a4e', craft: 40, dust: 10, order: 0 },
  silver: { name: 'シルバー', short: 'S', color: '#cfd8e8', craft: 120, dust: 30, order: 1 },
  gold: { name: 'ゴールド', short: 'G', color: '#ffd23f', craft: 500, dust: 100, order: 2 },
  legend: { name: 'レジェンド', short: 'L', color: '#ff5fd2', craft: 2000, dust: 400, order: 3 },
};
